dicionario_variaveis = {
  "gender": "Gênero",
  "age": "Idade",
  "height": "Altura (m)",
  "weight": "Peso (kg)",
  "family_history": "Histórico Familiar de Obesidade",
  "favc": "Consumo Frequente de Alimentos Calóricos",
  "fcvc": "Consumo de Vegetais",
  "ncp": "Número de Refeições por Dia",
  "caec": "Petiscos entre Refeições",
  "smoke": "Fumante",
  "ch2o": "Consumo de Água (litros/dia)",
  "scc": "Controle de Calorias",
  "faf": "Atividade Física (frequência)",
  "tue": "Tempo em Tela (TV, celular, computador)",
  "calc": "Consumo de Álcool",
  "mtrans": "Meio de Transporte",
  "obesity": "Nível de Obesidade",
  "imc": "Índice de Massa Corporal",
  "sedentario": "Sedentário",
  "faixa_personalizada": "Faixa Etária Personalizada"
}